baseURL = "/"
languageCode = "en-us"
title = "Ginlistic"
theme = "hugo-atlantic-theme"
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 10

[params]
  google_analytics_id = ""

  [params.homepage]
    postLimit = 6
    
  [params.logo]
    showLogoTextOnDesktop = true
    showLogoTextOnMobile = true
    showLogoImageOnDesktop = true
    showLogoImageOnMobile = true
    logoDesktopText = "Ginlistic"
    logoDesktopImage = "images/logo/logo.svg"
    logoMobileText = ""
    logoMobileImage = "images/logo/logo-mobile.svg"
    logoDesktopImageHeight = 32
    logoDesktopImageWidth = 32
    logoMobileImageHeight = 32
    logoMobileImageWidth = 32

  [params.fonts]
    google_fonts = "https://fonts.googleapis.com/css2?family=Fira+Mono&family=Lato:wght@300;400;700&family=Source+Sans+Pro&display=swap"
    heading = "Lato"
    base = "Source Sans Pro"
    monospace = "Fira Mono"

  [params.seo]
    meta_twitter_site = ""
    meta_twitter_creator = ""
    meta_og_image = ""

[build]
  writeStats = false

[permalinks]
    posts = ":slug/"
    pages = ":slug/"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"
  
# Main Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Japanese gins"
    url = "/categories/japan/"
    weight = 2

[[menu.main]]
    name = "Indian gins"
    url = "/categories/india/"
    weight = 2

[[menu.main]]
    name = "Tonic Waters"
    url = "/tonic-waters/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10